//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vika
{
    using System;
    using System.Collections.Generic;
    
    public partial class DolzhnostUser
    {
        public DolzhnostUser()
        {
            this.Persona = new HashSet<Persona>();
        }
    
        public int CodRol { get; set; }
        public string Rol { get; set; }
    
        public virtual ICollection<Persona> Persona { get; set; }
    }
}
