//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public Persona()
        {
            this.Polzovatel = new HashSet<Polzovatel>();
        }
    
        public int CodPerson { get; set; }
        public string LoginReg { get; set; }
        public string ParolReg { get; set; }
        public string Imia { get; set; }
        public string Telefon { get; set; }
        public string Pochta { get; set; }
        public string Pol { get; set; }
        public string Dolzhnost { get; set; }
        public Nullable<int> CodRol { get; set; }
    
        public virtual DolzhnostUser DolzhnostUser { get; set; }
        public virtual ICollection<Polzovatel> Polzovatel { get; set; }
    }
}
