//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polzovatel
    {
        public int CodPolzovatel { get; set; }
        public string LoginVhod { get; set; }
        public string ParolVhod { get; set; }
        public Nullable<int> CodPerson { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
